language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - "pip install -r requirements.txt"
  - export PYTHONPATH=$PYTHONPATH:$HOME/builds/lenarother/rxnconcompiler/:$HOME/builds/lenarother/rxnconcompiler/tests/

# command to run tests, e.g. python setup.py test
script: "python setup.py test"